name: "Terraform-run-manual"

on:
  workflow_dispatch:
    inputs:
      folder:
        description: "Folder project name"
        required: true
        default: ""
      tf_command:
        description: "Terrafom command for a run"
        required: true
        default: "apply"

jobs:
  terraform:
    name: "Terraform-deploy-manual"
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-central-1

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.4.2
          terraform_wrapper: false

      - name: Terraform Format
        id: fmt
        run: terraform -chdir=${{ github.event.inputs.folder }} fmt -check
        continue-on-error: true

      - name: Terraform Init Reconfigure
        id: init-reconfigure
        run: terraform -chdir=${{ github.event.inputs.folder }} init -reconfigure

      - name: Terraform Init
        id: init
        run: terraform -chdir=${{ github.event.inputs.folder }} init

      - name: Terraform Validate
        id: validate
        run: terraform -chdir=${{ github.event.inputs.folder }} validate -no-color

      - name: Terraform Plan
        id: plan
        run: terraform -chdir=${{ github.event.inputs.folder }} plan -no-color -input=false
        continue-on-error: true

      - name: Terraform Plan Status
        if: steps.plan.outcome == 'failure'
        run: exit 1

      - name: Terraform Apply/Destroy
        run: terraform -chdir=${{ github.event.inputs.folder }} ${{ github.event.inputs.tf_command }} -auto-approve -input=false
